---
title: "Inhoud minor"
output: html_document
---
> “Door de hele waardeketen zodanig in te richten dat de nieuwe technologieën optimaal kunnen bijdragen aan winsten op het gebied van efficiëntie en kwaliteit, ontstaat Smart Industry”

Gedurende 19 à 20 weken verzamel je samen met partners uit het bedrijfsleven (internationals, maar ook MKB-bedrijven) vraagstukken op het gebied van Smart Industry en bouw je in teamverband aan oplossingen. Je ontwikkelt een brede blik op de mogelijkheden en uitdagingen die Smart Industry biedt voor organisaties. 

Je zult zo veel mogelijk kennis vergaren en inspiratie opdoen via eigen observatie en praktijkervaring. De minor is ontwikkeld in nauwe samenwerking met partners uit het werkveld. Deze partners zullen ook actief deelnemen aan de uitvoering via workshops, hackathons, gastcolleges et cetera op verscheidene locaties. Aan het einde van de minor kun je in samenwerking met professionals uit verschillende disciplines een SMART-oplossing vertalen, ontwikkelen en uitvoeren voor een organisatie. 

Bij de inrichting van de minor is rekening gehouden met de verschillende achtergronden van de deelnemers en is een zodanige structuur gekozen dat iedere deelnemer optimaal kan werken aan zijn of haar kennisverbreding en -vaardigheden. Het programma is opgedeeld in afzonderlijke trajecten met thema’s die aansluiten bij je leerdoelen.

# Trajecten {.tabset .tabset-fade}

## Thema: Smart Start
Iedere deelnemer krijgt een inleiding tot Smart industry. Na afronding van dit traject kun je de mate van 'Smartness' van een organisatie beschrijven in een business case.

#### Feature 1: Customer intimacy
> "De ‘customer intimacy’ neemt toe. Niet alleen
doordat meer maatwerk wordt geleverd,
maar ook doordat klanten de mogelijk krijgen
in het ontwerpproces te participeren."

Uit: [Actieagenda SMART INDUSTRY 2014](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/pluginfile.php/310/mod_resource/content/1/smart-industry-actieagenda-lr.pdf)<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/xi1lPvycxiI" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 2: Value chain participation
> "Door digitalisering en
network centric production zullen waardeketens
veranderen en zal de samenwerking
worden versterkt."

Uit: [Actieagenda SMART INDUSTRY 2014](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/pluginfile.php/310/mod_resource/content/1/smart-industry-actieagenda-lr.pdf)<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/M5gys0RcH-s" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 3: Flexibilisation
> "Nieuwe productietechnologieën geven veel
vrijheid bij de productie. Het gemakkelijk
kunnen aanpassen van productieprocessen
leidt tot een hoge mate van flexibilisering."

Uit: [Actieagenda SMART INDUSTRY 2014](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/pluginfile.php/310/mod_resource/content/1/smart-industry-actieagenda-lr.pdf)<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/GKhSTjraHlU" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 4: Improving quality
> "De beschikbaarheid van data en de nieuwe
productietechnologieën versterken de kennis
over en controle op het productieproces,
waardoor de kwaliteit verbetert (bijvoorbeeld
zero defect)."

Uit: [Actieagenda SMART INDUSTRY 2014](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/pluginfile.php/310/mod_resource/content/1/smart-industry-actieagenda-lr.pdf)<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/BWgZXhm3WYM" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 5: Automation
> "Ten slotte zorgt verregaande robotisering
van de productie tot een verdere automatisering
van het productieproces."

Uit: [Actieagenda SMART INDUSTRY 2014](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/pluginfile.php/310/mod_resource/content/1/smart-industry-actieagenda-lr.pdf)<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/zPqHRGA5kx8" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 6: High value information
> "Op basis van digitalisering neemt de waarde
van informatie toe. Zo kan door inzet van
big data aan informatie worden verdiend."

Uit: [Actieagenda SMART INDUSTRY 2014](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/pluginfile.php/310/mod_resource/content/1/smart-industry-actieagenda-lr.pdf)<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/q7qElhGv7uY" frameborder="0" allowfullscreen></iframe>
<br>

## Thema: Smart Technology
Dit traject is gericht op studenten ICT of van een bedrijfskundige / -economische opleiding die zich beperkt of nooit verdiept hebben in techniek. Na afronding van dit traject ben je in staat om nieuwe technologieën op het gebied van IoT, Robotica en 3D-printen toe te passen op een praktijkcasus en in een business context plaatsen.

#### Feature 1: IoT
<iframe width="560" height="315" src="https://www.youtube.com/embed/HPRURtORnis" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 2: Robotics
<iframe width="560" height="315" src="https://www.youtube.com/embed/ECr4zgK6cPA" frameborder="0" allowfullscreen></iframe></iframe>
<br>

#### Feature 3: 3D Printing
<iframe width="560" height="315" src="https://www.youtube.com/embed/pZNTzkAR1Ho" frameborder="0" allowfullscreen></iframe>
<br>


## Thema: Smart Connection
Dit traject is gericht op studenten Techniek of van een bedrijfskundige / -economische opleiding die zich beperkt of nooit verdiept hebben in ICT. Na afronding van dit traject kun je nieuwe technologieën op het gebied van web, data, cloud en AI toepassen op een praktijkcasus en in een business context plaatsen.

#### Feature 1: Web Technologies
<iframe width="560" height="315" src="https://www.youtube.com/embed/IbYOYQ-uwj4" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 2: Web Development
<iframe width="560" height="315" src="https://www.youtube.com/embed/NlpK0-TLrjw" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 3: Data Analytics & Machine Learning
<iframe width="560" height="315" src="https://www.youtube.com/embed/pfFyZY1RPZU" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 4: Cloud Technologies
<iframe width="560" height="315" src="https://www.youtube.com/embed/HpPyhsC4q9M?list=PLOU2XLYxmsILe6_eGvDN3GyiodoV3qNSC" frameborder="0" allowfullscreen></iframe>
<br>




## Thema: Smart Business
Dit traject is gericht op studenten Techniek of ICT die zich beperkt of nooit verdiept hebben in de bedrijfskundige omgeving waarin ze straks zullen functioneren. Na afronding van dit traject kun je voor een opdrachtgever bedrijfsprocessen optimaliseren volgens Smart Industry criteria en de implicaties voor het gehele business model beschrijven.

#### Feature 1: De maatschappelijke en zakelijke uitdagingen
<iframe width="560" height="315" src="https://www.youtube.com/embed/9hkHAc1nku4" frameborder="0" allowfullscreen></iframe><br>

#### Feature 2: Slimme Klanten
<iframe width="560" height="315" src="https://www.youtube.com/embed/43GziWRaP8s" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 3: Slimme Processen
<iframe width="560" height="315" src="https://www.youtube.com/embed/ZCLHojIj7eA" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 4: Slim Investeren en Financieren
<iframe width="560" height="315" src="https://www.youtube.com/embed/I-JgtIiwX4M" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 5: Slim Informatie Gebruiken
<iframe width="560" height="315" src="https://www.youtube.com/embed/9IIgH0hNtgk" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 6: Slimme Werknemers
<iframe width="560" height="315" src="https://www.youtube.com/embed/-7EvZkcDa7s" frameborder="0" allowfullscreen></iframe>
<br>

#### Feature 7: Slimme Organisaties
<iframe width="560" height="315" src="https://www.youtube.com/embed/nLjFTHTgEVU?list=PLQjb7PbWSDVatTnWnc880u9m7LX0UHhwC" frameborder="0" allowfullscreen></iframe>
<br>
