---
title: "Onderwijs"
output: html_document
---

Bedrijven zijn dringend op zoek naar Smart Industry talent. Met deze minor krijg jij volop de gelegenheid om bedrijven te tonen hoe Smart jij bent. Een online leeromgeving biedt jou de faciliteiten om kennis op te doen, te oefenen, de voortgang te volgen en te communiceren. Voor een heel groot gedeelte bepaal je dus zelf waar en wanneer je wilt studeren. 

Kennismaking met de praktijk van Smart Industry speelt een prominente rol binnen de minor. Opgedane kennis zal zoveel mogelijk getoetst worden in de praktijk. Het is van belang dat je goed in een team kan samenwerken, want meestal zullen opdrachten in een team uitgevoerd worden voor en bij opdrachtgevers uit het bedrijfsleven. Echter, er is genoeg ruimte om eigen interesses te volgen en om individueel aan vraagstukken te werken.<br>

We gaan veel op pad om inspiratie op te doen bij bedrijven en instellingen.

<video width="640" height="480" controls>
  <source src="videos/Workshop SMR.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>

<p><cite>Workshop Robotica + Vision</cite> hosted by <a href="http://www.smrdelft.nl/" target="_blank">SMR Delft</a></p>

Door een continuous assessment is in principe iedere interactie met een activiteit of met betrokkenen een toets- en leermoment. Er zullen geen vaste tentamenmomenten zijn; geleidelijk bouw je een portfolio van bewijzen op en op basis daarvan zal de organisatie van de minor bepalen in hoeverre je bepaalde competenties hebt ontwikkeld.

Voldoe je aan de criteria van de minor, verdien je 30 EC. Voldoe je aan de criteria van het bedrijfsleven dan staat jou misschien wel een droombaan te wachten! 

